### ISSUE TITLE
Digitial Negatives support (.dng)

### ISSUE THREAD

**Issue by lrusak** [notspiff/imagedecoder.raw#2]
What about .dng files? It seems that imagedecoder.raw works for .dng if libraw is compiled with jpg support.
```
 --enable-jpeg    Enable JPEG support for Lossy compressed DNG files
```
also the mimetype and file extension need to be added to the addon.xml

**Comment by notspiff** [comment]
i will accept patches for enabling whichever format libraw support and which has been tested. i added those i have tested only. note, you will need the equivalent of https://github.com/xbmc/xbmc/pull/11086/commits/7c3b11746bfb85d91f25749aa2126ed8e00371d3

**Comment by lrusak** [comment]
I'm not sure I need to add a mime type because my files show up like so
```
file -b --mime-type 2010Mar13_0001.dng
image/tiff
```
but it seems like image/dng is actually a thing
https://www.filesuffix.com/en/extension/dng

**Comment by notspiff** [comment]
Kodi isnt smrt enough, it just does image/ext as a fallback. It is
necessary, I don't recall the details but it is, i spent some time
identifying the issue initially.

**Comment by notspiff** [comment]
this has been added.
